# Image URL to use all building/pushing image targets
VERSION ?= 0.1.3-snapshot
DOCKER_REPO := ghcr.io/opendataplatform
BUILDX_CACHE=/tmp/docker_cache

# You can switch between simple (faster) docker build or multiplatform one.
# For multiplatform build on a fresh system, do 'make docker-set-multiplatform-builder'
DOCKER_BUILD := docker buildx build --builder multiplatform --cache-to type=local,dest=$(BUILDX_CACHE),mode=max --cache-from type=local,src=$(BUILDX_CACHE) --platform linux/amd64,linux/arm64
#DOCKER_BUILD := docker build

# Comment this to just build locally
DOCKER_PUSH := --push


.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

.PHONY: dexgate
dexgate: version  ## Compile localy, in bin folder
	go build -o bin/dexgate main.go

version:
	@echo "// Generated by Makefile\n\npackage config\n\nvar Version = \"$(VERSION)\"\n" >internal/config/version_.go

doc: ## Generate doc index
	doctoc README.md --github --title '## Index'
# ------------------------------ Docker

.PHONY: docker
docker:  ## Build and push image
	$(DOCKER_BUILD) ${DOCKER_PUSH} -t $(DOCKER_REPO)/dexgate:$(VERSION) -f Dockerfile .

