APP_VERSION ?= 0.1.3-snapshot
DOCKER_TAG=${APP_VERSION}

IMG ?= quay.io/kubotal/dexgate:${DOCKER_TAG}

HELM_VERSION ?= 0.1.3-snapshot
HELM_DOCKER_REPO := quay.io/kubotal/charts

BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker


##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)


# ------------------------------ Build
##@ Build

.PHONY: build
build: version  ## Compile localy, in bin folder
	go build -o bin/dexgate main.go

version:
	@echo "// Generated by Makefile\n\npackage config\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/config/version_.go

# ------------------------------ Doc
##@ Doc

doc: ## Generate doc index
	doctoc README.md --github --title '## Index'

# ------------------------------ Docker
##@ Docker

.PHONY: docker
docker: version docker-build docker-push  ## Build docker image and push

.PHONY: docker-build
docker-build: version ## Build docker image
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image
	$(CONTAINER_TOOL) push ${IMG}


# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry (i.e. if you do not set a valid value via IMG=<myregistry/image:<tag>> then the export will fail)
# To adequately provide solutions that are compatible with multiple platforms, you should consider using this option.
#PLATFORMS ?= linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: version  ## Build and push dexgate image with cross-platform support
	- $(CONTAINER_TOOL) buildx create --name dexgate-builder --driver=docker-container
	- $(CONTAINER_TOOL) buildx build --builder dexgate-builder --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile .
	- $(CONTAINER_TOOL) buildx rm dexgate-builder



# ------------------------------ Chart
##@ Chart

define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: dexgate
version: $(HELM_VERSION)
sources:
  - https://github.com/kubotal/dexgate
appVersion: $(APP_VERSION)
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: ## Generate the helm/dexgate/Chart.yaml
	echo "$$CHART_YAML" >./helm/dexgate/Chart.yaml

.PHONY: chart
chart: chart-yaml ## Build and push dexgate helm chart
	cd ./helm && helm package -d ./../tmp dexgate && helm push ./../tmp/dexgate-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}

